### ISSUE TITLE
Zip code/find me form becomes unresponsive

### ISSUE THREAD

**Issue by jonjanelle** [OpenMaine/covid19-foodmap#25]
During testing MPA reported the following behavior:
"I accidentally clicked the “find me” button instead of the “search” button after typing in my ZIP code, and then (even after correcting myself) I couldn’t get it to display any data. I had to close the tab and reload the site."

**Comment by jonjanelle** [comment]
I wasn't able to reproduce this in Edge or Chrome. Could others give it a try?

**Comment by elburnett** [comment]
Couldn't do it in Firefox or Chrome.. the "locate me" didn't work in either

**Comment by congdon** [comment]
This doesn't work for me in Chrome, Firefox, or Safari on my laptop (and doesn't work in Safari on my phone).

**Comment by congdon** [comment]
On openmaine.org

**Comment by congdon** [comment]
Firefox v75.0, Mac 10.14.6
pantries.openmaine.org
Steps to reproduce: go to page and click 'locate me' button
Expected behavior:
  unknown, but either
  a. fill in the zipcode for me
  b. go ahead and open the map at that location

Actual behavior:
zipcode box turns red

(On Chrome, it's just a nothing -- nothing happens)
(On Safari, it's just a nothing -- nothing happens)

**Comment by jonjanelle** [comment]
I will remove the 'locate me' button. I think we're running into security issues with self-signed certs combined with differences in how browsers handle location permissions.

**Comment by congdon** [comment]
+1

**Comment by jonjanelle** [comment]
The 'Locate me' button has been removed
