### ISSUE TITLE
Call Portland pantries

### ISSUE THREAD

**Issue by elburnett** [OpenMaine/covid19-foodmap#63]

**Comment by JohnBrooking** [comment]
The goal, per the 5/8 meeting notes:
> ask about data coordination and solicit feedback

What are some specific questions we should include, and where do we record the answers? Is it permissible to add more columns or a new tab to the MPA sheet, or do they own that and wouldn't want us changing it too much? At the very least, I would suggest adding an ID# to the MPA sheet, so that other data resources could refer to those rows more precisely (per relational database standard practice).

My ideas for questions/talking points:
- Introduce the project
- Confirm they are okay with being included
- What data points they see as crucial to include (name, description, services, hours, URL, ...)
- Who to work with on a continuing basis to keep information up to date

Other thoughts?

**Comment by elburnett** [comment]
I see this as most important to ask:
- hours, any limits on who can get food, any other important info we should know as a website that's referring people to their pantry.

**Comment by jonjanelle** [comment]
What about a combination of the two like: 
- Brief intro and confirm they are okay with being included
- Hours, any limits on who can get food, any other important info we should know as a website that's referring people to their pantry.
- Who to work with on a continuing basis to keep information up to date

**Comment by JohnBrooking** [comment]
If everyone's good with @jonjanelle's combined question list, I'd like to propose recording responses by adding a new tab to the big MPA sheet, "Contact History" for example. (Too long? "Contact"? "History"?) This will keep individual instances of communication separate from the primary data on the Pantries tab, and be more manageable into the future, given that the pantries will continue to need to be contacted occasionally over time. The answers that impact the fields on the Pantries tab, such as hours and "active", can be copied to it whenever they change, so that sheet remains the "current" information, and the complete history is always available in the Contact History tab.

Also, I went ahead and added an "ID#" field in column A of the Pantries tab, and I envision that this would also appear on the Contact History tab, for accuracy.

**Comment by jonjanelle** [comment]
I'd suggest that we consider abandoning the idea of managing the data ourselves. Even if we call Portland pantries, that still leaves a great deal of additional data that we have not verified. If we're only able to vouch for the accuracy of Portland-area data, then we should not show data from other parts of the state. 

This task would also need to be completed on a recurring basis, and we do not currently have the volunteer base to support this. I recommend that we focus on evaluating whether GSFB is a reliable source as they appear to be updating their data regularly.

**Comment by jonjanelle** [comment]
Closing because the group no longer intends to actively maintain the data.
